# Common configurations for all services
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/} # Changed from eureka-server to discovery-service based on typical naming
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always
logging:
  level:
    org.springframework.security: INFO
    dev.skyang: DEBUG # Assuming this is a common application package prefix
