server:
  port: 9300 # Default, will be overridden by Docker Compose if needed
spring:
  application:
    name: availability-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME_AVAILABILITY:availabilitydb}
    username: ${DB_USERNAME_AVAILABILITY:user}
    password: ${DB_PASSWORD_AVAILABILITY:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Or 'validate' in prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
